--Limpa as tabelas
DELETE FROM Sessao_Produto;
DELETE FROM Sessao;
DELETE FROM Barco;
DELETE FROM Funcionario;
DELETE FROM Produto_Servico;
DELETE FROM Cliente;
DELETE FROM Cargo;
DELETE FROM Dono;
commit;

INSERT INTO DONO (ID_DONO, CNPJ, NOME_DONO) VALUES (1, '00.000.000/0001-00','Xavier Hublic');
select * from DONO;

INSERT INTO Cargo (NOME_CARGO, ID_CARGO, SALARIO, Carga_Horaria) VALUES ('Secretário', 1, 2000.00, 44);
INSERT INTO Cargo (NOME_CARGO, SALARIO, Carga_Horaria) VALUES ('Segurança', 2000.00, 44);
SELECT * FROM Cargo;

INSERT INTO Cliente (ID_CLIENTE, NOME_CLIENTE, CPF, data_nascimento, GENERO) VALUES (1, 'Creber da Silva', '000.000.001-00', TO_DATE('1996/01/01', 'yyyy/mm/dd'), 'CM');
--INSERT INTO Cliente (NOME_CLIENTE, CPF, data_nascimento, GENERO) VALUES ('Menor de idade', '000.000.002-00', sysdate, 'CM');
SELECT * FROM Cliente;

--INSERT INTO Cliente (NOME_CLIENTE, CPF, DATA_NASCIMENTO, GENERO) 
    --VALUES ('Menor de Idade Teste', '999.999.999-99', SYSDATE, 'M');

INSERT INTO Produto_Servico (NOME_PRODUTO_SERVICO, PRECO, ESTOQUE, ID_PRODUTO) VALUES ('Cerveja', 7.97, 10,1);
SELECT * FROM Produto_Servico;

INSERT INTO Funcionario (ID_FUNCIONARIO, NOME_FUNCIONARIO, CPF, ID_CARGO, GENERO, DATA_NASCIMENTO) VALUES (1, 'Meu Querido Secretário', '000.000.001-00', 1, 'CM', TO_DATE('2000/01/01', 'yyyy/mm/dd'));
--INSERT INTO Funcionario (NOME_FUNCIONARIO, CPF, ID_CARGO, GENERO, DATA_NASCIMENTO) VALUES ('Menor de idade', '000.000.001-00', 1, 'CM', sysdate);
SELECT * FROM Funcionario;


INSERT INTO Barco (ID_BARCO, NOME_BARCO, TIE, ID_DONO, Data_Fabricacao, Genero, ORIGEM, Preco, Comissao, Capacidade) VALUES (1, 'Wandersun', '000.000.001-00', 1, TO_DATE('1966/01/01', 'yyyy/mm/dd'), 'TW', 'BRASILEIRO', 100.00, 50, 3);
--INSERT INTO Barco (NOME_BARCO, TIE, ID_DONO, Data_Fabricacao, Genero, ORIGEM, Preco, Comissao, Capacidade) VALUES ('Menor de idade', '000.000.001-00', 1, sysdate, 'CM', 'BRASILEIRO', 100.00, 50, 3);
SELECT * FROM Barco;

INSERT INTO Sessao (ID_SESSAO, ID_BARCO, ID_CLIENTE, ID_FUNCIONARIO, DESCONTO) VALUES (1, 1, 1, 1, 0);
-- Altera a exibicao do formato da data antes do SELECT para poder ver as horas;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
SELECT * FROM Sessao;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';


INSERT INTO Sessao_Produto(ID_PRODUTO, ID_SESSAO, VALOR_UNITARIO, QNT) VALUES (1, 1, 7.97, 6);

INSERT INTO Sessao_Produto (ID_PRODUTO, ID_SESSAO, VALOR_UNITARIO, QNT) VALUES (1, 1, 7.97, 5);

SELECT * FROM Sessao_Produto;

SELECT NOME_PRODUTO_SERVICO, ESTOQUE 
FROM Produto_Servico 
WHERE ID_PRODUTO = 1;

SELECT NOME_CARGO, SALARIO FROM Cargo WHERE ID_CARGO = 1;

UPDATE Sessao SET DESCONTO = 10 WHERE ID_SESSAO = 1;

SELECT 
    FN_FATURAMENTO_DIA(EXTRACT(DAY FROM SYSDATE), EXTRACT(MONTH FROM SYSDATE), EXTRACT(YEAR FROM SYSDATE)) AS FATURAMENTO_HOJE,
    FN_FATURAMENTO_MES(EXTRACT(MONTH FROM SYSDATE), EXTRACT(YEAR FROM SYSDATE)) AS FATURAMENTO_MES_ATUAL,
    FN_FATURAMENTO_ANO(EXTRACT(YEAR FROM SYSDATE)) AS FATURAMENTO_ANO_ATUAL
FROM DUAL;

SELECT * FROM Sessao WHERE ID_SESSAO = 1;
SELECT NOME_PRODUTO_SERVICO, ESTOQUE FROM Produto_Servico WHERE ID_PRODUTO = 1;


COMMIT;