CREATE OR REPLACE FUNCTION FN_PRECO_BARCO(P_ID_BARCO NUMBER,P_INICIO DATE,P_FIM DATE)
RETURN NUMBER
IS
    V_PRECO_BARCO NUMBER;
    V_HORAS NUMBER;
BEGIN

    SELECT PRECO
    INTO V_PRECO_BARCO
    FROM BARCO
    WHERE ID_BARCO = P_ID_BARCO;

    V_HORAS := (P_FIM - P_INICIO) * 24;

    RETURN V_PRECO_BARCO * V_HORAS;

END;
/

CREATE OR REPLACE FUNCTION FN_ESTOQUE_DISPONIVEL(P_ID_PRODUTO NUMBER,P_QNT NUMBER)
RETURN BOOLEAN
IS
    V_ESTOQUE NUMBER;
BEGIN

    SELECT ESTOQUE
    INTO V_ESTOQUE
    FROM PRODUTO_SERVICO
    WHERE ID_PRODUTO = P_ID_PRODUTO;

    RETURN V_ESTOQUE >= P_QNT;

END;
/

CREATE OR REPLACE FUNCTION FN_BARCO_DISPONIVEL(P_ID_BARCO NUMBER)
RETURN BOOLEAN
IS
    V_QTD NUMBER;
BEGIN

    SELECT COUNT(*)
    INTO V_QTD
    FROM SESSAO
    WHERE ID_BARCO = P_ID_BARCO
      AND FIM IS NULL;

    RETURN V_QTD = 0;

END;
/

CREATE OR REPLACE FUNCTION FN_COMISSAO_DONO(P_ID_DONO NUMBER,P_DATA_INICIO DATE,P_DATA_FIM DATE)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN

    SELECT NVL(SUM(B.COMISSAO),0)
    INTO V_TOTAL
    FROM BARCO B
    JOIN SESSAO S
        ON S.ID_BARCO = B.ID_BARCO
    WHERE B.ID_DONO = P_ID_DONO
    AND S.FIM BETWEEN P_DATA_INICIO AND P_DATA_FIM;

    RETURN V_TOTAL;

END;
/

CREATE OR REPLACE FUNCTION FN_FATURAMENTO_MES(P_MES NUMBER,P_ANO NUMBER)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN

    SELECT NVL(SUM(VALOR_TOTAL),0)
    INTO V_TOTAL
    FROM SESSAO
    WHERE EXTRACT(MONTH FROM FIM)=P_MES
      AND EXTRACT(YEAR FROM FIM)=P_ANO;

    RETURN V_TOTAL;

END;
/

CREATE OR REPLACE FUNCTION FN_FATURAMENTO_ANO(P_ANO NUMBER)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN

    SELECT NVL(SUM(VALOR_TOTAL),0)
    INTO V_TOTAL
    FROM SESSAO
    WHERE EXTRACT(YEAR FROM FIM)=P_ANO;

    RETURN V_TOTAL;

END;
/

CREATE OR REPLACE FUNCTION FN_FATURAMENTO_DIA
(
    P_DIA NUMBER,
    P_MES NUMBER,
    P_ANO NUMBER
)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN

    SELECT NVL(SUM(VALOR_TOTAL),0)
    INTO V_TOTAL
    FROM SESSAO
    WHERE EXTRACT(DAY FROM FIM)=P_DIA
      AND EXTRACT(MONTH FROM FIM)=P_MES
      AND EXTRACT(YEAR FROM FIM)=P_ANO;

    RETURN V_TOTAL;

END;
/

