CREATE OR REPLACE TRIGGER TRG_RESTRINGE_IDADE_BARCOS
    BEFORE INSERT OR UPDATE ON BARCO
    FOR EACH ROW
DECLARE
    v_menor_idade exception;
BEGIN
    IF (not Maior_Dezoito(:New.Data_FABRICACAO))
    then 
       raise  v_menor_idade;
    end if;
exception 
    when v_menor_idade then 
        RAISE_APPLICATION_ERROR (-20067, 'BARCO MUITO NOVO');
    when others then
        RAISE_APPLICATION_ERROR (-20069, 'ERRO NAO IDENTIFICADO');
END TRG_RESTRINGE_IDADE;
/

CREATE OR REPLACE TRIGGER TRG_RESTRINGE_IDADE_CLIENTE
    BEFORE INSERT OR UPDATE ON CLIENTE
    FOR EACH ROW
DECLARE
    v_menor_idade exception;
BEGIN
    IF (not Maior_Dezoito(:New.Data_Nascimento))
    then 
       raise  v_menor_idade;
    end if;
exception 
    when v_menor_idade then 
        RAISE_APPLICATION_ERROR (-20067, 'CLIENTE MENOR DE IDADE');
    when others then
        RAISE_APPLICATION_ERROR (-20069, 'ERRO NAO IDENTIFICADO');
END TRG_RESTRINGE_IDADE;
/


CREATE OR REPLACE TRIGGER TRG_RESTRINGE_IDADE_FUNCIONARIO
    BEFORE INSERT OR UPDATE ON FUNCIONARIO
    FOR EACH ROW
DECLARE
    v_menor_idade exception;
BEGIN
    IF (not Maior_Dezoito(:New.Data_Nascimento))
    then 
       raise  v_menor_idade;
    end if;
exception 
    when v_menor_idade then 
        RAISE_APPLICATION_ERROR (-20067, 'FUNCIONARIO MENOR DE IDADE');
    when others then
        RAISE_APPLICATION_ERROR (-20069, 'ERRO NAO IDENTIFICADO');
END TRG_RESTRINGE_IDADE;
/

CREATE OR REPLACE TRIGGER TRG_INICIA_SESSAO
    BEFORE INSERT ON SESSAO
    FOR EACH ROW
BEGIN
    :NEW.INICIO := SYSDATE;
END TRG_INICIA_SESSAO;
/


CREATE OR REPLACE TRIGGER TRG_BAIXA_ESTOQUE
BEFORE INSERT ON SESSAO_PRODUTO FOR EACH ROW
DECLARE
    V_ESTOQUE NUMBER;
BEGIN

    SELECT ESTOQUE
    INTO V_ESTOQUE
    FROM PRODUTO_SERVICO
    WHERE ID_PRODUTO = :NEW.ID_PRODUTO;

    IF V_ESTOQUE < :NEW.QNT THEN
        RAISE_APPLICATION_ERROR(-20001,'ESTOQUE INSUFICIENTE');
    END IF;

    UPDATE PRODUTO_SERVICO
    SET ESTOQUE = ESTOQUE - :NEW.QNT
    WHERE ID_PRODUTO = :NEW.ID_PRODUTO;

END;
/


CREATE OR REPLACE TRIGGER TRG_QTD_BARCOS
AFTER INSERT ON BARCO
FOR EACH ROW
BEGIN
    UPDATE DONO
    SET QNT_BARCOS = QNT_BARCOS + 1
    WHERE ID_DONO = :NEW.ID_DONO;
END;
/

-- TRIGGER PARA DIMINUIR O ESTOQUE DE UM PRODUTO

-- TRUGGER QUE AUMENTA A QUANTIDADE DE BARCOS DA TABELA DONO

-- TRIGGER QUE VERIFICA SE TEM A QUANTIDADE DE ITENS QUE O CLIENTE QUER COMPRAR

-- COLOCAR UMA TRIGGER PARA A INSERÇAO EM CADA TABELA  QUE CHAMA AS PROCEDURES